# Generated by Django 4.2.14 on 2024-07-27 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('unit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('start_select_unit', models.DateTimeField()),
                ('end_select_unit', models.DateTimeField()),
                ('start_remove_add', models.DateTimeField()),
                ('end_remove_add', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='UserSessionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('midterm_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('session_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sessioncourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')])),
                ('label', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('session_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sessioncourse')),
            ],
        ),
    ]
